### ISSUE TITLE
Update to React Native 0.29, Null pointer exception (Android)

### ISSUE THREAD

**Issue by dkaluwila** [MattFoley/react-native-paypal#12]
I have recently updated the react native 0.27 to 0.29. Then moved package initialization to the application class from activity class , as we have to do this to support 0.29  (Android) that was the only change i did. After updating the RN, it will give null point exception 

```
                                                                  java.lang.NullPointerException
                                                                      at android.content.ComponentName.<init>(ComponentName.java:77)
                                                                      at android.content.Intent.<init>(Intent.java:3957)
                                                                      at br.com.vizir.rn.paypal.PayPal.startPayPalService(PayPal.java:93)
                                                                      at br.com.vizir.rn.paypal.PayPal.paymentRequest(PayPal.java:78)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                                      at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
                                                                      at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
                                                                      at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
                                                                      at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
                                                                      at java.lang.Thread.run(Thread.java:841)
```

 Is this  not supporting the 0.29 or i am doing something wrong?

**Comment by dkaluwila** [comment]
I was wrong this issue come if I initiate the paypal package in application class onCreat method. at that time activity context is null so that is why I got this issue simply moved initiating part to get package method it worked

**Comment by DeDuckProject** [comment]
There is work being done on this here:
 #https://github.com/Vizir/react-native-paypal/pull/11
Someone who knows the repo well can merge all of this?
